import fs from 'fs';
const content = fs.readFileSync('src/pages/NexusDF.tsx', 'utf8');

// Vou extrair o bloco BP inteiro e substituir por um bloco limpo.
const lines = content.split('\n');

const bpStart = lines.findIndex(l => l.includes("{activeStatementTab === 'BP' && ("));
const dmplStart = lines.findIndex(l => l.includes("{activeStatementTab === 'DMPL' && ("));

if (bpStart !== -1 && dmplStart !== -1) {
    const bpBlock = [
        "                {activeStatementTab === 'BP' && (",
        "                  <>",
        "                    {/* Summary Stats Overview - Responsive Cards */}",
        "                    <div className=\"grid grid-cols-2 md:grid-cols-4 gap-4 md:gap-6\">",
        "                         {[",
        "                           { key: 'caixa', id: '1.1.01' },",
        "                           { key: 'receita', id: '3.01' },",
        "                           { key: 'custo', id: '3.02' },",
        "                           { key: 'lucro', id: '3.06' }",
        "                         ].map(({ key, id }) => {",
        "                           const val = calculateLineValue(id, 'current');",
        "                           const hasIncomeAccounts = accounts.some(a => a.code.startsWith('4') || a.code.startsWith('5'));",
        "                           const isLucroPendente = key === 'lucro' && !hasIncomeAccounts;",
        "                           const displayVal = (key === 'lucro') ? val : Math.abs(val);",
        "",
        "                           return (",
        "                             <div key={key} className=\"bg-white dark:bg-slate-900 p-4 md:p-6 rounded-2xl md:rounded-3xl border border-slate-200 dark:border-slate-800 shadow-sm\">",
        "                               <span className=\"text-[8px] md:text-[10px] font-black uppercase text-slate-400 tracking-wider block mb-1 md:mb-2\">{(t.glossary as any)[key]}</span>",
        "                               <p className={cn(\"text-base md:text-2xl font-black truncate\", displayVal < 0 && key === 'lucro' ? \"text-rose-500\" : \"text-slate-900 dark:text-white\")}>",
        "                                 {isLucroPendente ? (",
        "                                   <span className=\"text-slate-300 italic text-xs\">Pendente</span>",
        "                                 ) : (",
        "                                   `R$ ${displayVal.toLocaleString(lang === 'pt' ? 'pt-BR' : 'en-US', { minimumFractionDigits: 0, maximumFractionDigits: 0 })}`",
        "                                 )}",
        "                                </p>",
        "                              </div>",
        "                           );",
        "                         })}",
        "                    </div>",
        "",
        "                    {/* BP Content Section */}",
        "                    <div className=\"grid grid-cols-1 lg:grid-cols-2 gap-8\">",
        "                       {/* Assets */}",
        "                       <div className=\"bg-white dark:bg-slate-900 rounded-[2.5rem] border border-slate-200 dark:border-slate-800 shadow-sm overflow-hidden flex flex-col\">",
        "                         <div className=\"p-8 border-b dark:border-slate-800 flex justify-between items-center bg-slate-50/50 dark:bg-slate-800/20\">",
        "                           <h3 className=\"text-xl font-black uppercase tracking-tight\">{t.statements.ativo}</h3>",
        "                         </div>",
        "                         <div className=\"p-4 md:p-8 flex-1 w-full overflow-x-hidden\">",
        "                           <table className=\"w-full text-xs md:text-sm table-auto\">",
        "                             <thead>",
        "                               <tr className=\"text-[10px] font-black uppercase text-slate-400 border-b dark:border-slate-800\">",
        "                                  <th className=\"px-2 md:px-4 py-3 text-left w-12\">Nota</th>",
        "                                  <th className=\"px-2 md:px-4 py-3 text-left\">Propriedade</th>",
        "                                  <th className=\"px-2 md:px-4 py-3 text-right\">2024</th>",
        "                                  <th className=\"px-2 md:px-4 py-3 text-right\">2023</th>",
        "                               </tr>",
        "                             </thead>",
        "                             <tbody>",
        "                               {STRUCTURE.BP_ATIVO.map((line, i) => {",
        "                                 const curr = calculateLineValue(line.id, 'current');",
        "                                 const prior = calculateLineValue(line.id, 'prior');",
        "                                 return (",
        "                                   <React.Fragment key={i}>",
        "                                     <tr ",
        "                                       className={cn(",
        "                                         \"border-b dark:border-slate-800/50\", ",
        "                                         line.isHeader ? \"bg-slate-50/50 dark:bg-slate-800/20\" : \"hover:bg-slate-50 transition-colors cursor-pointer\"",
        "                                       )}",
        "                                       onClick={() => !line.isHeader && setSelectedLineId(selectedLineId === line.id ? null : line.id)}",
        "                                     >",
        "                                       <td className=\"px-2 md:px-4 py-3 text-[10px] font-bold text-slate-300\">00</td>",
        "                                       <td className={cn(",
        "                                         \"px-2 md:px-4 py-3 font-bold flex items-center gap-2 whitespace-normal break-words\", ",
        "                                         line.indent && \"pl-4 md:pl-8 font-medium text-slate-600\", ",
        "                                         line.isHeader && \"text-indigo-600 uppercase text-[10px] md:text-[11px]\"",
        "                                       )}>",
        "                                         <span className=\"flex-1\">{line.label}</span>",
        "                                         {!line.isHeader && <ChevronRight className={cn(\"w-3 h-3 text-slate-300 flex-shrink-0 transition-transform\", selectedLineId === line.id && \"rotate-90\")} />}",
        "                                       </td>",
        "                                       <td className=\"px-2 md:px-4 py-3 text-right font-mono font-bold whitespace-nowrap\">{line.isHeader ? \"\" : curr.toLocaleString(lang === 'pt' ? 'pt-BR' : 'en-US')}</td>",
        "                                       <td className=\"px-2 md:px-4 py-3 text-right font-mono text-slate-400 whitespace-nowrap\">{line.isHeader ? \"\" : prior.toLocaleString(lang === 'pt' ? 'pt-BR' : 'en-US')}</td>",
        "                                     </tr>",
        "                                     {selectedLineId === line.id && (",
        "                                       <tr className=\"bg-slate-50 dark:bg-slate-800/50\">",
        "                                         <td colSpan={4} className=\"px-4 md:px-12 py-4\">",
        "                                           <div className=\"space-y-2\">",
        "                                             <div className=\"text-[10px] font-black uppercase text-slate-400 mb-2\">Composição do Saldo</div>",
        "                                             {getSourceAccounts(line.id).map((acc, idx) => (",
        "                                               <div key={idx} className=\"flex justify-between items-center text-[10px] md:text-[11px] gap-4\">",
        "                                                 <span className=\"text-slate-500 truncate\">{acc.code} - {acc.name}</span>",
        "                                                 <span className=\"font-bold flex-shrink-0\">R$ {acc.end.toLocaleString()}</span>",
        "                                               </div>",
        "                                             ))}",
        "                                           </div>",
        "                                         </td>",
        "                                       </tr>",
        "                                     )}",
        "                                   </React.Fragment>",
        "                                 );",
        "                               })}",
        "                             </tbody>",
        "                           </table>",
        "                         </div>",
        "                         <div className=\"bg-indigo-600 text-white font-black p-6 md:p-8 flex justify-between items-center\">",
        "                            <span className=\"text-xs md:text-sm uppercase tracking-widest\">{t.statements.totalAtivo}</span>",
        "                            <div className=\"flex gap-4 md:gap-8 text-right\">",
        "                               <div>",
        "                                  <span className=\"block text-[8px] opacity-60 uppercase mb-1\">2024</span>",
        "                                  <span className=\"font-mono text-base md:text-xl\">",
        "                                     {STRUCTURE.BP_ATIVO.filter(l => !l.isHeader).reduce((s, l) => s + calculateLineValue(l.id, 'current'), 0).toLocaleString()}",
        "                                  </span>",
        "                               </div>",
        "                               <div className=\"opacity-60\">",
        "                                  <span className=\"block text-[8px] uppercase mb-1\">2023</span>",
        "                                  <span className=\"font-mono text-base md:text-xl\">",
        "                                     {STRUCTURE.BP_ATIVO.filter(l => !l.isHeader).reduce((s, l) => s + calculateLineValue(l.id, 'prior'), 0).toLocaleString()}",
        "                                  </span>",
        "                               </div>",
        "                            </div>",
        "                         </div>",
        "                       </div>",
        "",
        "                       {/* Liabilities & Equity */}",
        "                       <div className=\"bg-white dark:bg-slate-900 rounded-[2.5rem] border border-slate-200 dark:border-slate-800 shadow-sm overflow-hidden flex flex-col\">",
        "                         <div className=\"p-8 border-b dark:border-slate-800 bg-slate-50/50 dark:bg-slate-800/20\">",
        "                           <h3 className=\"text-xl font-black uppercase tracking-tight\">{t.statements.passivo}</h3>",
        "                         </div>",
        "                         <div className=\"p-4 md:p-8 flex-1 w-full overflow-x-hidden\">",
        "                            <table className=\"w-full text-xs md:text-sm table-auto\">",
        "                             <thead>",
        "                               <tr className=\"text-[10px] font-black uppercase text-slate-400 border-b dark:border-slate-800\">",
        "                                  <th className=\"px-2 md:px-4 py-3 text-left w-12\">Nota</th>",
        "                                  <th className=\"px-2 md:px-4 py-3 text-left\">Propriedade</th>",
        "                                  <th className=\"px-2 md:px-4 py-3 text-right\">2024</th>",
        "                                  <th className=\"px-2 md:px-4 py-3 text-right\">2023</th>",
        "                               </tr>",
        "                             </thead>",
        "                             <tbody>",
        "                               {STRUCTURE.BP_PASSIVO.map((line, i) => {",
        "                                 const curr = calculateLineValue(line.id, 'current');",
        "                                 const prior = calculateLineValue(line.id, 'prior');",
        "                                 return (",
        "                                   <React.Fragment key={i}>",
        "                                     <tr ",
        "                                       className={cn(",
        "                                         \"border-b dark:border-slate-800/50\", ",
        "                                         line.isHeader ? \"bg-slate-50/50 dark:bg-slate-800/20\" : \"hover:bg-slate-50 transition-colors cursor-pointer\"",
        "                                       )}",
        "                                       onClick={() => !line.isHeader && setSelectedLineId(selectedLineId === line.id ? null : line.id)}",
        "                                     >",
        "                                       <td className=\"px-2 md:px-4 py-3 text-[10px] font-bold text-slate-300\">00</td>",
        "                                       <td className={cn(",
        "                                         \"px-2 md:px-4 py-3 font-bold flex items-center gap-2 whitespace-normal break-words\", ",
        "                                         line.indent && \"pl-4 md:pl-8 font-medium text-slate-600\", ",
        "                                         line.isHeader && \"text-indigo-600 uppercase text-[10px] md:text-[11px]\"",
        "                                       )}>",
        "                                         <span className=\"flex-1\">{line.label}</span>",
        "                                         {!line.isHeader && <ChevronRight className={cn(\"w-3 h-3 text-slate-300 flex-shrink-0 transition-transform\", selectedLineId === line.id && \"rotate-90\")} />}",
        "                                       </td>",
        "                                       <td className=\"px-2 md:px-4 py-3 text-right font-mono font-bold whitespace-nowrap\">{line.isHeader ? \"\" : (curr * -1).toLocaleString()}</td>",
        "                                       <td className=\"px-2 md:px-4 py-3 text-right font-mono text-slate-400 whitespace-nowrap\">{line.isHeader ? \"\" : (prior * -1).toLocaleString()}</td>",
        "                                     </tr>",
        "                                     {selectedLineId === line.id && (",
        "                                       <tr className=\"bg-slate-50 dark:bg-slate-800/50\">",
        "                                         <td colSpan={4} className=\"px-4 md:px-12 py-4\">",
        "                                           <div className=\"space-y-2\">",
        "                                             <div className=\"text-[10px] font-black uppercase text-slate-400 mb-2\">Composição do Saldo</div>",
        "                                             {getSourceAccounts(line.id).map((acc, idx) => (",
        "                                               <div key={idx} className=\"flex justify-between items-center text-[10px] md:text-[11px] gap-4\">",
        "                                                 <span className=\"text-slate-500 truncate\">{acc.code} - {acc.name}</span>",
        "                                                 <span className=\"font-bold flex-shrink-0\">R$ {(acc.end * -1).toLocaleString()}</span>",
        "                                               </div>",
        "                                             ))}",
        "                                           </div>",
        "                                         </td>",
        "                                       </tr>",
        "                                     )}",
        "                                   </React.Fragment>",
        "                                 );",
        "                               })}",
        "                             </tbody>",
        "                            </table>",
        "                         </div>",
        "                         <div className=\"bg-slate-900 text-white font-black p-6 md:p-8 flex justify-between items-center\">",
        "                            <span className=\"text-xs md:text-sm uppercase tracking-widest\">{t.statements.totalPassivo}</span>",
        "                            <div className=\"flex gap-4 md:gap-8 text-right\">",
        "                               <div>",
        "                                  <span className=\"block text-[8px] opacity-60 uppercase mb-1\">2024</span>",
        "                                  <span className=\"font-mono text-base md:text-xl\">",
        "                                     {(STRUCTURE.BP_PASSIVO.filter(l => !l.isHeader).reduce((s, l) => s + calculateLineValue(l.id, 'current'), 0) * -1).toLocaleString()}",
        "                                  </span>",
        "                               </div>",
        "                               <div className=\"opacity-60\">",
        "                                  <span className=\"block text-[8px] uppercase mb-1\">2023</span>",
        "                                  <span className=\"font-mono text-base md:text-xl\">",
        "                                     {(STRUCTURE.BP_PASSIVO.filter(l => !l.isHeader).reduce((s, l) => s + calculateLineValue(l.id, 'prior'), 0) * -1).toLocaleString()}",
        "                                  </span>",
        "                               </div>",
        "                            </div>",
        "                         </div>",
        "                       </div>",
        "                    </div>",
        "                  </>",
        "                )}",
        ""
    ];
    lines.splice(bpStart, dmplStart - bpStart, ...bpBlock);
}

fs.writeFileSync('src/pages/NexusDF.tsx', lines.join('\n'));
console.log('Clean BP rewrite applied');
